version: "3.9"
services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - '33061:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis_container
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
