-- Create table: short_urls
CREATE TABLE IF NOT EXISTS short_urls (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_code VARCHAR(16) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    expired_at DATETIME DEFAULT NULL,
    click_count INT UNSIGNED NOT NULL DEFAULT 0,
    creator_ip VARCHAR(45) DEFAULT NULL,
    user_agent TEXT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
